---
title: "MST marker bubble plots"
author: "Kelsey Jesser"
date: "9/22/2022"
output: html_document
---
**Prevalence of MST markers in Ecuadorian household samples**

Load libraries
```{r message=FALSE, warning=FALSE}
library(vegan)
library(reshape2)
library(ggpubr)
library(ggthemes)
library(ggplot2)
library(magrittr)
library(reshape2)
library(tidyr)
library(dplyr)
library(tibble)
library(janitor)
library(kableExtra)
```

Clear environment
```{r message=FALSE, warning=FALSE}
rm(list = ls())
```

Import data
```{r message=FALSE, warning=FALSE}
prev<-read.csv("prevalence_final_dataset.csv")
data<-read.csv("Phase II 09022022.csv")
```

Bubble plot
```{r message=FALSE, warning=FALSE}
#format data
counts<-prev %>%
  select(-matches("Number"))%>%
  select(-c("Site", "Household", "Sample_Code"))%>%
  melt(id.vars= c("Sample_Type"))%>%
  group_by(Sample_Type, variable)%>%
  summarize(cnt=n())

sums<- prev %>%
  select(-matches("Number"))%>%
  select(-c("Site", "Sample_Code", "Household"))%>%
  melt(id.vars= c("Sample_Type"))%>%
  group_by(Sample_Type, variable)%>%
  summarise(across(value, sum))

prev_sampletype<-data.frame(Sample_Type=counts$Sample_Type, 
                            Assay=counts$variable, 
                            Total_Samples=counts$cnt, 
                            Total_Pos=sums$value, 
                            Percent_Pos=sums$value/counts$cnt*100)

prev_sampletype_balloon<-prev_sampletype %>%
  subset(Assay != "Human_positive" & Assay != "Any_positive")

#plot
prev_sampletype_balloon$Assay <- factor(prev_sampletype_balloon$Assay, levels = c("Rum2Bac", "Pig2Bac", "GFD", "DG37", "HF183", "Any_animal_pos", "Any_source_spec_pos", "GenBac"))

labels<-c("Rum2Bac (ruminant)", "Pig2Bac (pig)", "GFD (poultry)", "DG37 (dog)", "HF183 (human)", "Any animal marker", "Any source-\nassociated marker", "GenBac (general)")

a<-ggballoonplot(prev_sampletype_balloon, 
             x="Sample_Type",
             y="Assay",
             fill="Assay", 
             size="Percent_Pos",
             ggtheme=theme_minimal())+
  scale_fill_tableau()+
  scale_y_discrete(labels=labels)+
  ggtitle("Prevalence of MST markers")+
  guides(fill = "none",
         size=guide_legend(title="Percent positive\nsamples"))+
  theme(axis.text.y=element_text(size=14),
        axis.text.x=element_text(size=14), 
        legend.background=element_rect(color=NA),
        legend.text=element_text(size=12),
        legend.title=element_text(size=13),
        panel.border=element_rect(color="black", fill=NA))
  
  
  a
```

Bubble plot without any source and any animal
```{r message=FALSE, warning=FALSE}
#format data
counts<-prev %>%
  select(-matches("Number"))%>%
  select(-c("Site", "Household", "Sample_Code"))%>%
  melt(id.vars= c("Sample_Type"))%>%
  group_by(Sample_Type, variable)%>%
  summarize(cnt=n())

sums<- prev %>%
  select(-matches("Number"))%>%
  select(-c("Site", "Sample_Code", "Household"))%>%
  melt(id.vars= c("Sample_Type"))%>%
  group_by(Sample_Type, variable)%>%
  summarise(across(value, sum))

prev_sampletype<-data.frame(Sample_Type=counts$Sample_Type, 
                            Assay=counts$variable, 
                            Total_Samples=counts$cnt, 
                            Total_Pos=sums$value, 
                            Percent_Pos=sums$value/counts$cnt*100)

prev_sampletype_balloon<-prev_sampletype %>%
  subset(Assay != "Human_positive" & Assay != "Any_positive" & Assay != "Any_animal_pos" & Assay != "Any_source_spec_pos")


kbl(prev_sampletype_balloon)%>%
  kable_styling(latex_options="scale_down", font_size=10)%>%
  kable_minimal()

#plot
prev_sampletype_balloon$Assay <- factor(prev_sampletype_balloon$Assay, levels = c("Rum2Bac", "Pig2Bac", "GFD", "DG37", "HF183", "GenBac"))

labels<-c("Rum2Bac (ruminant)", "Pig2Bac (pig)", "GFD (poultry)", "DG37 (dog)", "HF183 (human)", "GenBac (general)")


cols <- c("GenBac"="#FF9DA7", "HF183"="#59A14F", "DG37"="#76B7B4", "GFD"="#E15759", "Pig2Bac"="#F28E2B", "Rum2Bac"="#4E79A7")

b<-ggballoonplot(prev_sampletype_balloon, 
             x="Sample_Type",
             y="Assay",
             fill="Assay", 
             size="Percent_Pos",
             ggtheme=theme_minimal())+
  scale_fill_manual(values=cols, labels=scales::percent)+
  scale_y_discrete(labels=labels)+
  #scale_x_discrete(labels=labels2)+
  ggtitle("Prevalence of MST markers")+
  guides(fill = "none",
         size=guide_legend(title="Positive\nsamples (%)"))+
  theme(axis.text.y=element_text(size=14),
        axis.text.x=element_text(size=14), 
        legend.background=element_rect(color=NA),
        legend.text=element_text(size=12),
        legend.title=element_text(size=13),
        panel.border=element_rect(color="black", fill=NA))
  
  
  b
```


Overall prevalence by assay
```{r message=FALSE, warning=FALSE}
perc_all<-data.frame(GenBac=(sum(prev$GenBac))/586*100, 
                     HF183=(sum(prev$HF183))/586*100, 
                     DG37=(sum(prev$DG37))/586*100, 
                     GFD=(sum(prev$GFD))/586*100,
                     Pig2Bac=(sum(prev$Pig2Bac))/586*100,
                     Rum2Bac=(sum(prev$Rum2Bac))/586*100)

kbl(perc_all)%>%
  kable_styling(latex_options="scale_down", font_size=10)%>%
  kable_minimal()

```

Number of detections by sample type
```{r message=FALSE, warning=FALSE}
prev_melt<-prev %>%
  melt(id.vars=c("Sample_Code", "Sample_Type", "Site", "Household"), variable.name=("measurement"), value.name="value")
  
detections<-prev%>%
  select(-c(11:17))%>%
  melt(id.vars=c("Sample_Code", "Sample_Type", "Site", "Household"), variable.name=("measurement"), value.name="value")%>%
  group_by(Sample_Type, measurement)%>%
  summarize(count=sum(value, na.rm=TRUE))

detections_host<-prev%>%
  select(-c(GenBac, 11:17))%>%
  melt(id.vars=c("Sample_Code", "Sample_Type", "Site", "Household"), variable.name=("measurement"), value.name="value")%>%
  group_by(Sample_Type, measurement)%>%
  summarize(count=sum(value, na.rm=TRUE))

kbl(detections_host)%>%
  kable_styling(latex_options="scale_down", font_size=10)%>%
  kable_minimal()

```


